---
title: Voeg een uiterlijk aan een sprite toe
hero_image: images/banner.png
description: Voeg een uiterlijk aan een sprite toe
version: 4
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - title: Voeg een uiterlijk aan een sprite toe
