---
title: Voeg uiterlijken aan een sprite toe
hero_image: images/banner.png
description: scratch3-add-costumes-to-a-sprite description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - 
    title: Voeg uiterlijken aan een sprite toe
