title: scratch3-add-costumes-to-a-sprite
hero_image: images/banner.png
description: scratch3-add-costumes-to-a-sprite description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
