title: Add a costume to a sprite
hero_image: images/banner.png
description: Add a costume to a sprite
version: 4
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - title: Add a costume to a sprite
