---
title: स्प्राइटमध्ये पोशाख जोडा
hero_image: प्रतिमा / banner.png
description: स्प्राइटमध्ये पोशाख जोडा
version: 0
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - 
    title: आपल्या स्प्राईटला पोशाख घाला
