---
title: Colocar uma fantasia em um ator
hero_image: images/banner.png
description: Colocar uma fantasia em um ator
version: 4
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - title: Colocar uma fantasia em um ator
