---
title: Přidání kostýmu postavě
hero_image: images/banner.png
description: Přidání kostýmu postavě
version: 4
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - 
    title: Přidání kostýmu postavě
