---
title: Añade un disfraz a un objeto
hero_image: images/banner.png
description: Añade un disfraz a un objeto
version: 4
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - title: Añade un disfraz a un objeto
