---
title: Lägg till en klädsel till en sprajt
hero_image: images/banner.png
description: Lägg till en klädsel till en sprajt
version: 4
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - 
    title: Lägg till en klädsel till en sprajt
