---
title: Ajouter des costumes à un sprite
hero_image: images/banner.png
description: description scratch3-ajouter-costumes-à-un-sprite
version: 4
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - 
    title: Ajouter des costumes à un sprite
