---
title: Ajouter des costumes à un sprite
hero_image: images/banner.png
description: Ajouter un costume à un sprite
version: 4
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - 
    title: Ajouter un costume à un sprite
