---
title: Aggiungi un costume a una immagine
hero_image: images/banner.png
description: Aggiungi un costume a una immagine
version: 4
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - 
    title: Aggiungi un costume a una immagine
